// <auto-generated />
using System;
using Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Models.Cost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name");

                    b.Property<int>("PlanId");

                    b.HasKey("CostId");

                    b.HasIndex("Deleted");

                    b.HasIndex("PlanId");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("Database.Models.CostDetail", b =>
                {
                    b.Property<int>("CostDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CostId");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Deleted");

                    b.Property<int>("Value");

                    b.HasKey("CostDetailId");

                    b.HasIndex("CostId");

                    b.HasIndex("Date");

                    b.HasIndex("Deleted");

                    b.ToTable("CostsDetails");
                });

            modelBuilder.Entity("Database.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("End");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Start");

                    b.Property<int?>("UserId");

                    b.HasKey("PlanId");

                    b.HasIndex("Deleted");

                    b.HasIndex("End");

                    b.HasIndex("Start");

                    b.HasIndex("UserId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Database.Models.PlanMember", b =>
                {
                    b.Property<int>("PlanMemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlanId");

                    b.Property<int?>("UserId");

                    b.HasKey("PlanMemberId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("PlanMembers");
                });

            modelBuilder.Entity("Database.Models.Spend", b =>
                {
                    b.Property<int>("SpendId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int>("CostDetailId");

                    b.Property<int>("OrderNumber");

                    b.Property<int?>("UserId");

                    b.Property<int>("Value");

                    b.HasKey("SpendId");

                    b.HasIndex("CostDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("Spends");
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.HasIndex("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Database.Models.Cost", b =>
                {
                    b.HasOne("Database.Models.Plan", "Plan")
                        .WithMany("Costs")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.CostDetail", b =>
                {
                    b.HasOne("Database.Models.Cost", "Cost")
                        .WithMany("CostDetails")
                        .HasForeignKey("CostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.Plan", b =>
                {
                    b.HasOne("Database.Models.User", "User")
                        .WithMany("Plans")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Database.Models.PlanMember", b =>
                {
                    b.HasOne("Database.Models.Plan", "Plan")
                        .WithMany("PlanMembers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("PlanMembers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Database.Models.Spend", b =>
                {
                    b.HasOne("Database.Models.CostDetail", "CostDetail")
                        .WithMany("Spends")
                        .HasForeignKey("CostDetailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("Spend")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
